name: Variables and Secrets
on: [push]

jobs:
  decrypt-file:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt file
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" \
            --output $HOME/secrets/secret.json secret.json.gpg

      - name: View Encrypted File
        run: cat $HOME/secrets/secret.json

  log-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ secrets.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ secrets.REPO_LEVEL_VAR }}
      ORG_LEVEL_VAR: ${{ secrets.ORG_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "This step ran because BOOLEAN_SECRET is true"

      - name: Log Vars
        run: |
          echo '${{ vars.JOBS_RUNNER }}'
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
          echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"
